// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.DAL.DataContext;

namespace ToDoList.WebApp.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    partial class AppDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Todo.Domain.Entities.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TodoLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(1400),
                            Description = "test list",
                            Title = "My list",
                            Updated = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(1613),
                            UserId = new Guid("ae50b1f6-bc08-48b1-9a2d-8afca4a5d4f9")
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(2115),
                            Description = "test list",
                            Title = "My list2",
                            Updated = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(2133),
                            UserId = new Guid("ae50b1f6-bc08-48b1-9a2d-8afca4a5d4f9")
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(2157),
                            Description = "test list",
                            Title = "My list 3",
                            Updated = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(2160),
                            UserId = new Guid("0a2395b4-c238-4987-8ad3-8ccb43d250bd")
                        });
                });

            modelBuilder.Entity("Todo.Domain.Entities.TodoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskListId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TaskListId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(4803),
                            Description = "test",
                            EndDate = new DateTime(2022, 7, 25, 8, 57, 29, 790, DateTimeKind.Local).AddTicks(2415),
                            Priority = 0,
                            Status = 0,
                            TaskListId = 1,
                            Title = "Buy milk",
                            Updated = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(4981)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(5554),
                            Description = "test",
                            EndDate = new DateTime(2022, 7, 25, 8, 57, 29, 790, DateTimeKind.Local).AddTicks(5498),
                            Priority = 1,
                            Status = 0,
                            TaskListId = 2,
                            Title = "Buy coffee",
                            Updated = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(5562)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(5585),
                            Description = "test",
                            EndDate = new DateTime(2022, 7, 25, 8, 57, 29, 790, DateTimeKind.Local).AddTicks(5577),
                            Priority = 2,
                            Status = 0,
                            TaskListId = 1,
                            Title = "Do nothing",
                            Updated = new DateTime(2022, 7, 25, 7, 57, 29, 790, DateTimeKind.Local).AddTicks(5587)
                        });
                });

            modelBuilder.Entity("Todo.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae50b1f6-bc08-48b1-9a2d-8afca4a5d4f9"),
                            Created = new DateTime(2022, 7, 25, 7, 57, 29, 786, DateTimeKind.Local).AddTicks(2518),
                            Email = "user1@gmail.com",
                            Password = "aaabb1C#",
                            UpdatedAt = new DateTime(2022, 7, 25, 7, 57, 29, 788, DateTimeKind.Local).AddTicks(7502),
                            UserName = "Firstuser1"
                        },
                        new
                        {
                            Id = new Guid("0a2395b4-c238-4987-8ad3-8ccb43d250bd"),
                            Created = new DateTime(2022, 7, 25, 7, 57, 29, 788, DateTimeKind.Local).AddTicks(8597),
                            Email = "userno2@wp.pl",
                            Password = "bbbAFF##C1",
                            UpdatedAt = new DateTime(2022, 7, 25, 7, 57, 29, 788, DateTimeKind.Local).AddTicks(8614),
                            UserName = "SecondUser22"
                        },
                        new
                        {
                            Id = new Guid("841a4b33-4181-4553-aaab-c9cffef86196"),
                            Created = new DateTime(2022, 7, 25, 7, 57, 29, 788, DateTimeKind.Local).AddTicks(8962),
                            Email = "testUser3@gmail.com",
                            Password = "test#PassworD!",
                            UpdatedAt = new DateTime(2022, 7, 25, 7, 57, 29, 788, DateTimeKind.Local).AddTicks(8966),
                            UserName = "thirdtestUser3"
                        });
                });

            modelBuilder.Entity("Todo.Domain.Entities.TodoList", b =>
                {
                    b.HasOne("Todo.Domain.Entities.User", "User")
                        .WithMany("TodoLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Todo.Domain.Entities.TodoTask", b =>
                {
                    b.HasOne("Todo.Domain.Entities.TodoList", "TodoList")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("Todo.Domain.Entities.TodoList", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Todo.Domain.Entities.User", b =>
                {
                    b.Navigation("TodoLists");
                });
#pragma warning restore 612, 618
        }
    }
}
